- features/manage-position/Create.tsx
- features/manage-position/Deposit.tsx
- features/manage-position/Redeem.tsx
- features/manage-position/Withdraw.tsx
Fixes errors in computing the collateralization ratio in Deposit and Withdraw.
Fixes weirdness in displaying a past-expiry time for a withdraw request.
Blocks off other pages when there's a pending withdrawal request (because all other txns will fail).
Adds collateral input validation based on available balance for Create and Deposit.
Adds input validation for cases where the user doesn't have enough synthetic balance to Redeem.
> Fix minor bugs and add guardrails to prevent reverting txns

- features/manage-position/Create.tsx
- features/manage-position/Deposit.tsx
- features/manage-position/Redeem.tsx
- features/manage-position/Withdraw.tsx
This will allow these transactions to estimate their own gas. With a gas limit of 7MM, most of these transactions would ask the user to send $20+ in gas for all of these transactions even though they would really only use a fraction of that.
I'm having trouble testing this in a mainnet fork, but I've done some light testing on mainnet to verify that Ethers correctly estimates gas when this parameter is left out. @adrianmcli, since you have a lot of experience with Ethers, could you verify that this should, indeed, work and give the user a reasonable gas limit?
> Remove gas limit

- features/manage-position/Withdraw.tsx
Otherwise, this can create an issue where it appears as if the user's CR is above the GCR, so a fast withdrawal is possible, but the UI doesn't allow you to do it.
> Current GCR should have the same precision as user's expected CR

- features/manage-position/Redeem.tsx
Fixes #17 
This limits the ability to redeem tokens such that your resulting balance will be less than the `minSponsorTokens` count.
> add minSponsorTokens to limit max redeem tokens

- package.json
- tsconfig.json
Next.js requires Typescript compiler options of `"module": "esnext"`, while the `chain.ts` script requires `"module": "commonjs"`. To get around this, we explicitly run the `chain.ts` command with a compiler option to force `commonjs` modules.
References:
- https://github.com/TypeStrong/ts-node/issues/992
- https://github.com/vercel/next.js/issues/7361#issuecomment-494975798
> make chain script use different config from frontend

- features/manage-position/Create.tsx
Resolves #23 
Open question: Should we add this error message to Deposit/Redeem/Withdraw/Transfer as well? Currently they all display the error message whe `collateral === null` which is something to the effect of "you need a position to do this action".
> Add new error message to Create if user has not selected an EMP

- features/contract-state/GeneralInfo.tsx
- features/manage-position/Create.tsx
- features/manage-position/Deposit.tsx
- features/manage-position/ManagePosition.tsx
- features/manage-position/Withdraw.tsx
- features/manage-position/YourPosition.tsx
- features/manage-position/YourWallet.tsx
Divides CR and GCR by pricefeed's `latestPrice` wherever it is displayed to end user. I took care not to add in the `latestPrice` into existing CR calculations that determine whether the user can execute EMP position management actions. This is because these actions all happen on invisible to the user. Instead, I calculated new variables from the existing CR's and using the `latestPrice` and displayed these new "priced" CR's to the end user.
Resolves #13 
> Connect PriceFeed to `manage-position` Components

- features/contract-state/Totals.tsx
- utils/getExchangeLinks.ts
Previously we hardcoded the uniswap base URL for an exchange link, this no longer works since yUSD is exchanged on Balancer.
This is potentially way too much work to achieve this functionality, but I created a module `getExchangeLinks` that provides a mapping function from `emp.tokenSymbol ==> getExchangeLink()` where `getExchangeLink()` is a function that takes in some input and returns a URL to the exchange where you can trade for the token symbol. In the future if our tokens trade on other exchanges like Matcha then we can build off of this module to easily add other types of exchanges.
Open to suggestions for a more succinct way of achieving this dynamism.
> Add dynamic links to exchanges to buy collateral or synthetic tokens

- containers/EmpSponsors.ts
- features/all-positions/AllPositions.tsx
- pages/_app.tsx
- pages/index.tsx
Resolves #84  
Resolves #83 
I also moved `cRatio` and `liquidationPrice` to the EMPSponsors.ts container instead of calculating it in the AllPositions.tsx component.
Attribution: heavily inspired by [uniswap.info's](https://github.com/Uniswap/uniswap-info/blob/v2/src/components/PairList/index.js) [pagination](https://uniswap.info/home)!
> Add column sorting and pagination to EMP sponsors table

- apollo/balancer/queries.ts
- apollo/uma/queries.ts
- containers/Balancer.ts
- features/yield/BalancerData.tsx
- By default, the UMA subgraph returns 100 positions for the `positions` query but we have > 140 so I set this to the max 1000 (follow up PR will have to figure out how pagination works for the subgraph)
- Add `shares` query to Balancer data to see number of unique contributors. Also only allowed to query up to 1000
> Increase query count + add shareholder data

- apollo/uma/queries.ts
- containers/DvmContract.ts
- containers/DvmState.ts
- containers/EmpState.ts
- features/contract-state/GeneralInfo.tsx
- features/manage-position/ManagePosition.tsx
- features/manage-position/MethodSelector.tsx
- features/manage-position/SettleExpired.tsx
- pages/_app.tsx
- utils/getDocLinks.ts
If a contract is expired, the user will only see the "Settle" method option. Otherwise, they will see "Create/Deposit/Redeem/Withdraw" but no "Settle"
It allows user to call `expire()` if a contract has expired but has not requested a price yet, and allows either a sponsor or a tokenholder to call `settleExpired()`. The dApp calls `Voting.hasPrice` in order to determine whether a price request has been resolved. Once a price has been resolved, a button to settle expired will appear.
It also provides a Max-Approve button for token holders.
Resolves #102
> SettleExpired Feature

- containers/Connection.ts
- features/contract-state/Totals.tsx
This PR adds a simple button to add the synthetic token to your metamask wallet. Additionally, this PR hides etherscan & market links until the user has selected a contract from the dropdown list.
Open question: do we want this functionality? main issue is the token is limited to 6 chars in eip747. This is pretty painful as we loose token information (see screenshot).
> implemented eip747

- containers/Position.ts
- features/manage-position/Create.tsx
- features/manage-position/Deposit.tsx
- features/manage-position/Redeem.tsx
- features/manage-position/SettleExpired.tsx
- features/manage-position/Withdraw.tsx
- features/manage-position/YourLiquidations.tsx
- features/manage-position/YourPosition.tsx
- features/weth/Weth.tsx
There are two problems here:
- The "Max" button in the Redeem feature sets the max amount to redeem equal to the user's balance, even if they have more tokens than # tokens outstanding in their position. This needs to be set to `Math.min(tokenBalance, tokensInPosition)`
- The amount set to the max is equal to the "intended max" amount casted to a number, and JS casting loses precision. Therefore, the amount set to the max should be equal to the string. This affects both Redeem and UnwrapWETH
Fixes #116
> "Max Buttons" incorrectly calculate max amounts to Redeem and Unwrap-Weth

- apollo/uma/queries.ts
- containers/EmpSponsors.ts
- features/all-positions/AllLiquidations.tsx
Look at the row for sponsor beginning 0x6B for the difference:
Current site only shows one liquidation for a sponsor:
This fix slightly modifies the key used to store liquidation data to capture multiple liqs per sponsor:
> EMPSponsors Container: use sponsor+liqID as key instead of sponsor to display multiple liquidations for sponsors

- features/all-positions/AllLiquidations.tsx
- features/all-positions/LiquidationActionDialog.tsx
- features/all-positions/PositionActionsDialog.tsx
- features/manage-position/Deposit.tsx
This PR adds the ability to "click and dispute" a liquidation. Additionally, a dialog is added to show additional liquidation information in the "liquidations table". The screenshots below showcase this new functionality in different app states:
**Refined liquidations table**: The liquidations table was refined to have a more consistent look. 
1) Each section heading was made bold. 
2) Consistent widths and wrapping in each column.
3) removed one additional column to enable the full width without need to scroll.
4) changed the order of columns for consistency and to simplify the table.
5) hover color effect is the same as in PR #40.
**Additional liquidation information after liquidation liveness** If the timestamp is past the liquidation liveness then the dialog shows additional …
> Click to dispute logic

- apollo/client.ts
- containers/Connection.ts
- containers/EmpSponsors.ts
- containers/WethContract.ts
- features/all-positions/LiquidationActionDialog.tsx
- features/emp-selector/EMPs.ts
- features/emp-selector/useEmpList.ts
- features/yield/Yield.tsx
- Switch seamlessly between Kovan and Mainnet contracts for WETH and EMP contracts
- Refuse to render `Yield` page when on Kovan because most of the balancer pool data here is irrelevant to Kovan
- Add support for Kovan subgraph URL
Question: 
- Is it possible to specify via `onboard.js` which networks we support? For example, I'd like this warning to show only if the user's network is not mainnet or kovan:
Other:
- Fixes bug in "Click To Dispute" feature where liquidation ID is incorrectly passed into `dispute()` method
Fixes #86
> Add kovan contracts

- apollo/uma/queries.ts
- containers/EmpSponsors.ts
Due to a subgraph bug, ended sponsor positions (following `settleExpired` calls by sponsors, for example) set `isEnded` to true, as expected, but do not reset `collateral` to 0 because this call reverts once the position actually is deleted. See the order of contract actions:
```
delete positions[msg.sender];
emit EndedSponsorPosition(msg.sender);
```
> fix(all-sponsors): Parse out `isEnded` positions from UMA graph query

- features/manage-position/Deposit.tsx
- features/manage-position/Redeem.tsx
- features/manage-position/Withdraw.tsx
Redeem/Deposit/Withdraw shouldn't render if position has 0 collateral, I changed this to a number check rather than a string check which was incorrectly catching "0" instead of "0.0".
> fix(manage-position) fix check for detecting 0 collateral

- README.md
- features/all-positions/PositionActionsDialog.tsx
Fixes #129 
Some previews:
New rows showing current, min, and max collateral ratios:
Warning user if they set maxCollPerToken too high:
Warning a user if they set minCollPerToken too low:
Error shown to user if the position's cratio is outside their specified min/max bounds:
Rendering shown if only one bound is exceeded:
> feat(click-to-liquidate): Block invalid min/maxCollPerToken

- features/emp-selector/EMPs.ts
- utils/getOffchainPrice.ts
1 EMP expires at 4pm UTC Sep 3, test out expiry
1 EMP expires at 10pm UTC Sep 3, to mirror production contract
Changes Kraken to Bitstamp price provider to mirror [UMIP7](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-7.md)
> Add updated renBTC collateral contracts

- features/manage-position/Create.tsx
Avoids edge case where `max` sets tokens to a CR === GCR, `Math.floor(x - some_small_amount)` is cleaner.
> fix(Create): floor max tokens to create instead of rounding to arbitrary precision

- containers/Balancer.ts
- features/yield/BalancerData.tsx
- features/yield/FarmingCalculator.tsx
- features/yield/Yield.tsx
- features/yield/YieldCalculator.tsx
This PR fixes an issue in the yield calculator for renBTC. Before this PR, the balancer graphQL query expects the `tokensList` in the pools had the synth token USDC token address in an array. This works for `yUSD-SEP20` and `yUSD-OCT20`. However for `uUSDrBTC-OCT` this order has flipped around. To accommodate any direction, this PR modifies the `YIELD_TOKENS` object to store a string-array key-value object to store relevant balancer lookups with the correct token ordering.
> fix(yield-calculator) fix pool inconsistancies

- features/all-positions/PositionActionsDialog.tsx
We have had users burnt from not realizing that they are interacting with a position that is not theirs. This PR places an alert if this is the case in the deposit screen.
> feat(liquidation-dialog): warn user if they are looking at a position that is not theirs

- features/emp-selector/EMPs.ts
- utils/getOffchainPrice.ts
Adds `uUSDrETH-Nov20` and `uUSDrBTC-Nov20` kovan contracts that were deployed via the newly [deployed EMP creator](https://github.com/UMAprotocol/protocol/pull/1997)
> improve(emps-list): add November EMP's deployed with new EMP Creator

- containers/Token.ts
- features/manage-position/Redeem.tsx
- utils/convertToWeiSafely.ts
This button is supposed to set the amount to redeem to either the user's balance or the total position debt, depending on which is larger.
However, the comparison is comparing two numbers that have had their precision potentially reduced, so we should be comparing the two numbers using the same precision.
> fix(redeem): MAX button on Redeem page sets incorrectly

- features/manage-position/Withdraw.tsx
Tiny fix for countdown not adding a leading 0 for minutes and seconds < 10.
> fix withdrawal countdown missing padding for minutes and seconds

- containers/Balancer.ts
- containers/EmpSponsors.ts
- features/yield/FarmingCalculator.tsx
- features/yield/Yield.tsx
- pages/index.tsx
- utils/yieldTokenList.ts
- Farming calc page was not resetting `rewardToken = null` when the selected EMP changes, which falsely displayed the Farming calc for non eligible tokens
- CoinGeckoAPI was getting pinged constantly (> 100 a second at least), I added a check to see if we previously loaded token price data
- GraphQL queries were refreshing every few seconds in the background, I removed this polling functionality
Fixes #168 
Fixes #167
> improve(performance) & fix(farming calc): Remove unneccessary queries and fix farming calc fix

- features/all-positions/AllSponsors.tsx
Small fix to address an incorrect assumption in the all positions table with the tooltip wording.
> fix inverted price feed wording on liquidation Tooltip

- containers/EmpState.ts
- features/manage-position/SettleExpired.tsx
- features/yield/Yield.tsx
It is possible that DVM has not resolved a price but EMP has an `expiryPrice()` (if the DVM has been upgraded since the EMP's expiry), and its possible that an EMP has no `expiryPrice()` but the DVM has resolved a price (right after the DVM has finished its reveal round but before anyone has attempted to `settle()` on the EMP)
> improve(expiry): Should check for `expiryPrice` on EMP contract in addition to DVM resolved price

- features/all-positions/LiquidationActionDialog.tsx
- features/contract-state/DisputeParams.tsx
This PR does two things:
1) The liquidation liveness is not shown on the "General Info" table. Normally, this is the same as withdrawal liveness but this is not strictly the case. This PR adds this information.
After this PR the dispute params looks as follows.
2) there was an error in the liquidations table, as documented in #185 where the `LiquidationActionDialog` incorrectly displayed the liquidation time remaining due to incorrect variable usage.
close #185
> feat&fix(liquidation-liveness) add liquidation liveness to General Info and fix liquidation table

- features/yield/YieldCalculator.tsx
- jest.config.js
- package.json
- utils/calculators.test.ts
- utils/calculators.ts
- yarn.lock
This PR adds compounding interest calculator and uses that to calculate APY. It also renames APR to APY.
It also adds several dependencies to allow for unit testing. This theoretically would allow testing of react components, but more work would be needed in order for that to work 100%.
see: https://www.omnicalculator.com/finance/apy
compare to:
compare to:
Closes #187
> fix(yield): changed the way APY is calculated, add jest for unit tests

- features/contract-state/Totals.tsx
before this PR:
After this PR:
And still scales as expected on mobile:
> fix(syling): padding on home page on to deal with so many tokens 🤑

- constants/rewards.ts
- features/yield/FarmingCalculator.tsx
- The month in `Date.UTC()` is supposed to be zero-indexed
- The farming calc hard-codes liquidity rewards to 1/2 of dev mining rewards, but mistakenly computes dev mining rewards for the current EMP address even when the roll is currently undergoing. In these situations, the dev mining rewards should be computed for the EMP from which the roll is occurring (i.e. the "old" EMP)
- Adds an end-date to DEC contracts so that they stop showing rewards post-roll.
Overall, this entire liquidity mining calculator clearly needs a makeover.
> fix(farming-calculator): Fix how dev mining rewards are calculated mid-roll + other small fixes

- containers/DevMining.ts
- utils/calculators.ts
Signed-off-by: David <david@umaproject.org>
Motivation #202 
This makes 2 major changes to EMP calculation:
- DevMining container now imports the active emplist from our github which @smb2796 and I maintain
- Previous EMP valuation was based off of total collateral locked. This changes it to synthetic minted, and attempts to get a price from coingecko, otherwise fallsback to 1 dollar, which most synthetics are. 
This produces much better results and are very close to this weeks payouts:
- yd eth estimates 7,886.682  vs [payout ](https://github.com/UMAprotocol/protocol/pull/2499)of 7080 
- yd btc estimates 8,681.799 vs [payout ](https://github.com/UMAprotocol/protocol/pull/2500)of 9067 
Closes #202
> fix(calculators): update EMP valuation to use synthetic, and import active emp list

- utils/calculators.ts
- utils/getCoinGeckoTokenPrice.ts
- utils/getOffchainPrice.ts
Signed-off-by: David <david@umaproject.org>
motivation #205 
Simply adds new cors proxy wrapper to bitstamp url. Adds as helper function in case we need to do this for other urls as well. 
Also updates coingecko calls to remove uncessessary header info, did not run into issues after this change, but verify if you can. 
fixes #205
> fix(emp-tools): change cors proxy and cleanup other requests

- utils/calculators.test.ts
- utils/calculators.ts
motivation #207
Previous calculation would fallback to 1 doller per token if a token price wasnt available. This caused a problem for some contracts where tokens are worth much more than 1 dollar. This now falls back to the value of the collateral locked in the emp and divides it by the collateralization ratio to estimate token minted. This could lead to large over estimation in some cases.
New Estimations:
Previous week dev mining calcs:
```
"0x3a93E863cb3adc5910E6cea4d51f132E8666654F": "191.374666273330978411",
"0xaB3Aa2768Ba6c5876B2552a6F9b70E54aa256175": "4.525277475441628788",
"0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8": "14733.426577007680355462",
"0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5": "17180.933058155691222569",
"0xeAddB6AD65dcA45aC3bB32f88324897270DA0387": …
```
> fix(emp-tools): improve dev mining calc by falling back to collateral value if no token value

- apollo/client.ts
protofire/uma subgraph is unsynced, uma-protocol/uma synced as of yesterday after patched a bug on mainnet.
> patch(apollo): Change subgraph URL

- containers/ContractList.ts
- containers/ContractState.ts
- containers/EmpContract.ts
- containers/EmpState.ts
- containers/SelectedContract.ts
- pages/_app.tsx
- utils/Contracts.ts
- utils/getAbi.ts
Signed-off-by: David <david@umaproject.org>
#214
This allows emp contracts to work with different interfaces, mainly renaming of Pct functions to Percentage.  This switches the EmpState container to use the new and more general ContractState container under the hood. This leverages a new 'getState' function bound to each contract abi to allow both getting and mapping contract state into a form compatible with the views.
Another PR will be needed in order to fix decimalization between synthetic and collateral
> feat: get emp v2 contract state working

- constants/rewards.ts
This pr fixes the roll logic in `rewards.ts` to calculate YD-BTC-JUN's APY correctly.
> fix(rewards): Fix YD-BTC APR

- utils/getCoinGeckoTokenPrice.ts
Signed-off-by: David <david@umaproject.org>
#222 
Adds a caching period of 10 minutes for coingecko fetches.  Maybe this is too long, but I think it would be ok.  I'm seeing better results when loading the page, dev mining calculations seem to work consistently now.
closes #222
> fix: add 10 min cache to coingecko calls to prevent rate limit

- apollo/uniswap/queries.ts
- constants/perpetuals.ts
- containers/PerpetualState.ts
- containers/Uniswap.ts
- features/contract-selector/ContractSelector.tsx
- features/contract-state/TabbedView.tsx
- features/perpetual/contract-state/ContractState.tsx
- features/perpetual/contract-state/GeneralInfo.tsx
- features/perpetual/contract-state/PerpetualInfo.tsx
- features/perpetual/contract-state/TabbedView.tsx
- pages/_app.tsx
- pages/index.tsx
- utils/Contracts.ts
- utils/calculators.ts
#204 
- Add perp specific boxes for fair value, funding rate and market price
- adds helper utilities for uniswap gql calls
- clears out perp general info component and totals due to incompatibility with emp state
This needs a lot more work to be production ready, but this is for future work.
- custom containers for getting perp specific state for the general info component
- fixing existing containers to not fetch data based on emp abis 
- position managment tab
>  feat: add perpetual info boxes, clean up non working components

- apollo/client.ts
- apollo/uma/queries.ts
- features/perpetual/contract-state/TabbedView.tsx
**motivation**
#204 
**summary**
This enables viewing all positions and for adding deposits and liquidating.  This leverages the work @nicholaspai has done with the uma subgraph and is using his recently updated code which supports the perp on kovan.
**screens**
**issue**
closes #204
> fix: change subgraph url and adjust query to get positions

- containers/EmpSponsors.ts
- features/all-positions/LiquidationActionDialog.tsx
fixes #233 
clubhouse: https://app.clubhouse.io/uma-project/story/970/disable-or-hide-the-ability-to-dispute-a-liquidation-from-emp-tools
**summary**
looks like issue was caused by minor change in subgraph api. liquidation and dispute addresses now are on `liquidator` and `disputer` rather than before `liquidator.address` and `disputer.address`
> fix: fix liquidator/disputer addresses to fix modal issue
