UMAprotocol/emp-tools

features/manage-position/Deposit.tsx
features/manage-position/Redeem.tsx
features/manage-position/Withdraw.tsx

Add etherscan url link to deposit/redeem/withdraw

---

apollo/client.ts
apollo/queries.ts
containers/EmpSponsors.ts
containers/PriceFeed.ts
features/all-positions/AllPositions.tsx
package.json
pages/_app.tsx
utils/getOffchainPrice.ts
yarn.lock

Resolves #32 
Stretch TODO: Add a loading graphic while graph query `loading === true`.

Use UMA subgraph data for sponsor table

---

chain.ts
features/manage-position/Create.tsx
features/manage-position/Deposit.tsx
features/manage-position/Redeem.tsx
features/manage-position/Withdraw.tsx
package.json
pages/index.tsx

This PR adds a command to the `package.json` to lint the repo. Along with this, the repo is linted.

Lint Repo & update package.json

---

features/manage-position/Create.tsx
pages/index.tsx

Fix Master <-- Develop merge conflicts 

---

apollo/queries.ts
containers/EmpSponsors.ts

Patch for new subgraph interface

---

apollo/balancer/queries.ts

Only count pool LPs with balance > 0

---

containers/PriceFeed.ts
features/all-positions/AllPositions.tsx
features/contract-state/GeneralInfo.tsx
features/manage-position/YourPosition.tsx
utils/getOffchainPrice.ts

Since the list of sources is now > 1, its too bulky to list all sources in multiple components. I removed the list of source exchanges from AllPositions and YourPosition.
I added a `Label` to GeneralInfo to display a list of exchanges in order to save more horizontal space.
Resolves #80

Refactor `getOffchainPrice` to handle additional pricefeed sources

---

features/yield/FarmingCalculator.tsx
features/yield/Yield.tsx
features/yield/YieldCalculator.tsx
utils/getUmaTokenPrice.ts

Refactor all null/invalid variable value checking to as early as possible in contract.
Resolves #68 , follows pattern in all other existing files.

Refactor all null/invalid variable value checking in Yield & Farming Calculator

---

README.md

@mrice32 @chrismaree do we have a staging site now?

Remove staging link

---

apollo/balancer/queries.ts
containers/Balancer.ts
features/yield/FarmingCalculator.tsx

Try the staging site and sign in with your sponsor wallet, the Liquidity Mining tab should auto detect your BPT share!
Fixes #99

Autodetect user's BPT share of pool if they are signed in

---

containers/Position.ts
features/manage-position/YourPosition.tsx

- Display requested withdrawal amount in YourPosition
- Calculate CR using req. withdrawal amount
- Display backing collateral (locked collateral - req withdrawal amount) in YourPosition
Part of #122 
Preview:

Reflect withdrawal request in CR and backing collateral for token debt

---

containers/Balancer.ts
features/yield/FarmingCalculator.tsx
features/yield/Yield.tsx
features/yield/YieldCalculator.tsx

Checks if user has selected a yToken against a list of yield tokens, default is the yUSD-SEP20 token.
Queries balancer pool data from yield token.
Also adds information about farming UMA during roll between SEPT and OCT
Preview prior to roll on august 28 23:00 UTC:
Preview after roll:

feat(balancer-container): Auto detect relevant Balancer pool to query data from

---

features/yield/FarmingCalculator.tsx

feat(farming-calc): Point BAL calculator to pools.vision instead of predictions.exchange

---

features/manage-position/Create.tsx

- added tooltip to max and min buttons
- removed auto fill as it was buggy and sometimes didn't allow user to override it, and its hard to reason about

Add "Max" button create to create max amount of tokens with entered collateral

---

features/manage-position/Create.tsx
features/yield/FarmingCalculator.tsx

- reduce "max" tokens in Create so that GCR constraint is always met
- Hide countdown to roll when time is up

fix(general): two nit fixes

---

pages/index.tsx
pages/terms.tsx

@hlambur requested that I throw up a first draft of this. This should be reviewed by a real lawyer.

Add terms of service

---

features/contract-state/GeneralInfo.tsx
features/emp-selector/EMPs.ts

feat(emp-list): Replace expired yUSD-SEP20 token with a "perpetual" yUSD-SEP30

---

containers/Balancer.ts
features/all-positions/PositionActionsDialog.tsx
features/yield/FarmingCalculator.tsx

Fixes #149 
Fixes #150 
Fixes #153 
Fixes #154

fix(farming-calc): farming calc + remove auto-refresh + must select deposit or liquidate

---

features/manage-position/Withdraw.tsx

This small PR adds a little feature to the request withdrawal page to show the progress of a withdrawal request.

feat(request withdrawal) Added progress bar

---

features/yield/FarmingCalculator.tsx

- APR does not change based on inputted share of pool, should always display
- Removed hard coded values in reward token object

fix(farming-calc) APR should not depend on pool share, refactor reward token object

---

features/yield/FarmingCalculator.tsx

This PR adds rewards calculations on the "to" contract in a roll.

fix(farming-calculator) add calculator on roll-to contract for Dec contracts.

---

features/yield/Yield.tsx

improve(yield): Display temporary yield page redirecting to balancer pools as long as balancer subgraph is returning inaccurate information

---

features/yield/Yield.tsx

fix(yield-temp): Explain how to calculate APY

---

features/yield/Yield.tsx

Balancer subgraph appears correct, reverting temp page now

improve(farming-calc) revert temp calc page

---

features/contract-state/Totals.tsx
package.json
yarn.lock

This PR is in response to issue #191 to fix connection issues with wallet connect. After upgrading the version of onboard.js wallet connect works again within the connector. 
I have tested this in Chrome, Safari, and Firefox and was able to generate and send transactions from all browsers.

fix(wallet-connector) upgrade onboard.js

---

constants/docLinks.ts

Fix links in `constants/docLinks.ts` which were broken

fix(constants): update docs links

---

apollo/uma/queries.ts
containers/EmpSponsors.ts
utils/Contracts.ts

added a new kovan contract `0x95b597b6fa71f9f42a93b83149b4d835a6176596` and fixed issue when querying for more than 100 financial contracts

fix: query more than 100 financial contracts
